version: '3'

services:
  slack-docker:
    image: shadowkrusha/docker-slack
    environment:
      # Adjust as required
      webhook: https://hooks.slack.com/########
      include_hostname: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    deploy:
      mode: global

